# Generated by Django 5.1 on 2024-09-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=150)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_hub.area')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_hub.specialization')),
            ],
        ),
    ]
