# Generated by Django 5.1 on 2024-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_hub', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default_doc.jpg', upload_to='profile_pics'),
        ),
    ]
