# Generated by Django 5.1 on 2024-09-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_hub', '0004_alter_doctor_area_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_hub.area'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_hub.specialization'),
        ),
    ]
